// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/slice_service.proto

package onossliceservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultType int32

const (
	ResultType_FAIL    ResultType = 0
	ResultType_SUCCESS ResultType = 1
)

var ResultType_name = map[int32]string{
	0: "FAIL",
	1: "SUCCESS",
}

var ResultType_value = map[string]int32{
	"FAIL":    0,
	"SUCCESS": 1,
}

func (x ResultType) String() string {
	return proto.EnumName(ResultType_name, int32(x))
}

func (ResultType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{0}
}

type DbaType int32

const (
	DbaType_DBA_TYPE_SR_DBA DbaType = 0
	DbaType_DBA_TYPE_CO_DBA DbaType = 1
)

var DbaType_name = map[int32]string{
	0: "DBA_TYPE_SR_DBA",
	1: "DBA_TYPE_CO_DBA",
}

var DbaType_value = map[string]int32{
	"DBA_TYPE_SR_DBA": 0,
	"DBA_TYPE_CO_DBA": 1,
}

func (x DbaType) String() string {
	return proto.EnumName(DbaType_name, int32(x))
}

func (DbaType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{1}
}

type DeviceStatus int32

const (
	DeviceStatus_UP   DeviceStatus = 0
	DeviceStatus_DOWN DeviceStatus = 1
)

var DeviceStatus_name = map[int32]string{
	0: "UP",
	1: "DOWN",
}

var DeviceStatus_value = map[string]int32{
	"UP":   0,
	"DOWN": 1,
}

func (x DeviceStatus) String() string {
	return proto.EnumName(DeviceStatus_name, int32(x))
}

func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{2}
}

type DeviceType int32

const (
	DeviceType_WB_OLT_1G  DeviceType = 0
	DeviceType_WB_OLT_10G DeviceType = 1
	DeviceType_WB_OLT_25G DeviceType = 2
	DeviceType_WB_OLT_50G DeviceType = 3
)

var DeviceType_name = map[int32]string{
	0: "WB_OLT_1G",
	1: "WB_OLT_10G",
	2: "WB_OLT_25G",
	3: "WB_OLT_50G",
}

var DeviceType_value = map[string]int32{
	"WB_OLT_1G":  0,
	"WB_OLT_10G": 1,
	"WB_OLT_25G": 2,
	"WB_OLT_50G": 3,
}

func (x DeviceType) String() string {
	return proto.EnumName(DeviceType_name, int32(x))
}

func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{3}
}

type UniTags struct {
	PonCTag              string   `protobuf:"bytes,1,opt,name=pon_c_tag,json=ponCTag,proto3" json:"pon_c_tag,omitempty"`
	UniPortName          string   `protobuf:"bytes,2,opt,name=uni_port_name,json=uniPortName,proto3" json:"uni_port_name,omitempty"`
	DbaType              string   `protobuf:"bytes,3,opt,name=dba_type,json=dbaType,proto3" json:"dba_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UniTags) Reset()         { *m = UniTags{} }
func (m *UniTags) String() string { return proto.CompactTextString(m) }
func (*UniTags) ProtoMessage()    {}
func (*UniTags) Descriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{0}
}

func (m *UniTags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UniTags.Unmarshal(m, b)
}
func (m *UniTags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UniTags.Marshal(b, m, deterministic)
}
func (m *UniTags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniTags.Merge(m, src)
}
func (m *UniTags) XXX_Size() int {
	return xxx_messageInfo_UniTags.Size(m)
}
func (m *UniTags) XXX_DiscardUnknown() {
	xxx_messageInfo_UniTags.DiscardUnknown(m)
}

var xxx_messageInfo_UniTags proto.InternalMessageInfo

func (m *UniTags) GetPonCTag() string {
	if m != nil {
		return m.PonCTag
	}
	return ""
}

func (m *UniTags) GetUniPortName() string {
	if m != nil {
		return m.UniPortName
	}
	return ""
}

func (m *UniTags) GetDbaType() string {
	if m != nil {
		return m.DbaType
	}
	return ""
}

type BandwidthInfos struct {
	Rf                   uint32   `protobuf:"varint,1,opt,name=rf,proto3" json:"rf,omitempty"`
	Ra                   uint32   `protobuf:"varint,2,opt,name=ra,proto3" json:"ra,omitempty"`
	Rs                   uint32   `protobuf:"varint,3,opt,name=rs,proto3" json:"rs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BandwidthInfos) Reset()         { *m = BandwidthInfos{} }
func (m *BandwidthInfos) String() string { return proto.CompactTextString(m) }
func (*BandwidthInfos) ProtoMessage()    {}
func (*BandwidthInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{1}
}

func (m *BandwidthInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BandwidthInfos.Unmarshal(m, b)
}
func (m *BandwidthInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BandwidthInfos.Marshal(b, m, deterministic)
}
func (m *BandwidthInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BandwidthInfos.Merge(m, src)
}
func (m *BandwidthInfos) XXX_Size() int {
	return xxx_messageInfo_BandwidthInfos.Size(m)
}
func (m *BandwidthInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_BandwidthInfos.DiscardUnknown(m)
}

var xxx_messageInfo_BandwidthInfos proto.InternalMessageInfo

func (m *BandwidthInfos) GetRf() uint32 {
	if m != nil {
		return m.Rf
	}
	return 0
}

func (m *BandwidthInfos) GetRa() uint32 {
	if m != nil {
		return m.Ra
	}
	return 0
}

func (m *BandwidthInfos) GetRs() uint32 {
	if m != nil {
		return m.Rs
	}
	return 0
}

// Requests
type AddSliceGroupRequest struct {
	SliceId              uint32   `protobuf:"varint,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	DeviceId             string   `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PortName             string   `protobuf:"bytes,3,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`
	TotalBandwidth       uint32   `protobuf:"varint,4,opt,name=total_bandwidth,json=totalBandwidth,proto3" json:"total_bandwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSliceGroupRequest) Reset()         { *m = AddSliceGroupRequest{} }
func (m *AddSliceGroupRequest) String() string { return proto.CompactTextString(m) }
func (*AddSliceGroupRequest) ProtoMessage()    {}
func (*AddSliceGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{2}
}

func (m *AddSliceGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSliceGroupRequest.Unmarshal(m, b)
}
func (m *AddSliceGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSliceGroupRequest.Marshal(b, m, deterministic)
}
func (m *AddSliceGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSliceGroupRequest.Merge(m, src)
}
func (m *AddSliceGroupRequest) XXX_Size() int {
	return xxx_messageInfo_AddSliceGroupRequest.Size(m)
}
func (m *AddSliceGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSliceGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSliceGroupRequest proto.InternalMessageInfo

func (m *AddSliceGroupRequest) GetSliceId() uint32 {
	if m != nil {
		return m.SliceId
	}
	return 0
}

func (m *AddSliceGroupRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *AddSliceGroupRequest) GetPortName() string {
	if m != nil {
		return m.PortName
	}
	return ""
}

func (m *AddSliceGroupRequest) GetTotalBandwidth() uint32 {
	if m != nil {
		return m.TotalBandwidth
	}
	return 0
}

type AddSliceRequest struct {
	SliceName            string          `protobuf:"bytes,1,opt,name=slice_name,json=sliceName,proto3" json:"slice_name,omitempty"`
	SliceId              uint32          `protobuf:"varint,2,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	DeviceId             string          `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PortName             string          `protobuf:"bytes,4,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`
	Tags                 *UniTags        `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	BwInfos              *BandwidthInfos `protobuf:"bytes,6,opt,name=bwInfos,proto3" json:"bwInfos,omitempty"`
	TrafficContainers    []uint32        `protobuf:"varint,7,rep,packed,name=traffic_containers,json=trafficContainers,proto3" json:"traffic_containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddSliceRequest) Reset()         { *m = AddSliceRequest{} }
func (m *AddSliceRequest) String() string { return proto.CompactTextString(m) }
func (*AddSliceRequest) ProtoMessage()    {}
func (*AddSliceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{3}
}

func (m *AddSliceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSliceRequest.Unmarshal(m, b)
}
func (m *AddSliceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSliceRequest.Marshal(b, m, deterministic)
}
func (m *AddSliceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSliceRequest.Merge(m, src)
}
func (m *AddSliceRequest) XXX_Size() int {
	return xxx_messageInfo_AddSliceRequest.Size(m)
}
func (m *AddSliceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSliceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSliceRequest proto.InternalMessageInfo

func (m *AddSliceRequest) GetSliceName() string {
	if m != nil {
		return m.SliceName
	}
	return ""
}

func (m *AddSliceRequest) GetSliceId() uint32 {
	if m != nil {
		return m.SliceId
	}
	return 0
}

func (m *AddSliceRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *AddSliceRequest) GetPortName() string {
	if m != nil {
		return m.PortName
	}
	return ""
}

func (m *AddSliceRequest) GetTags() *UniTags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AddSliceRequest) GetBwInfos() *BandwidthInfos {
	if m != nil {
		return m.BwInfos
	}
	return nil
}

func (m *AddSliceRequest) GetTrafficContainers() []uint32 {
	if m != nil {
		return m.TrafficContainers
	}
	return nil
}

type DeviceStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceStatusRequest) Reset()         { *m = DeviceStatusRequest{} }
func (m *DeviceStatusRequest) String() string { return proto.CompactTextString(m) }
func (*DeviceStatusRequest) ProtoMessage()    {}
func (*DeviceStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{4}
}

func (m *DeviceStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceStatusRequest.Unmarshal(m, b)
}
func (m *DeviceStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceStatusRequest.Marshal(b, m, deterministic)
}
func (m *DeviceStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceStatusRequest.Merge(m, src)
}
func (m *DeviceStatusRequest) XXX_Size() int {
	return xxx_messageInfo_DeviceStatusRequest.Size(m)
}
func (m *DeviceStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceStatusRequest proto.InternalMessageInfo

type GetETCDRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetETCDRequest) Reset()         { *m = GetETCDRequest{} }
func (m *GetETCDRequest) String() string { return proto.CompactTextString(m) }
func (*GetETCDRequest) ProtoMessage()    {}
func (*GetETCDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{5}
}

func (m *GetETCDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetETCDRequest.Unmarshal(m, b)
}
func (m *GetETCDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetETCDRequest.Marshal(b, m, deterministic)
}
func (m *GetETCDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetETCDRequest.Merge(m, src)
}
func (m *GetETCDRequest) XXX_Size() int {
	return xxx_messageInfo_GetETCDRequest.Size(m)
}
func (m *GetETCDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetETCDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetETCDRequest proto.InternalMessageInfo

// Responses
type AddSliceGroupResponse struct {
	Type                 ResultType `protobuf:"varint,1,opt,name=type,proto3,enum=onossliceservice.ResultType" json:"type,omitempty"`
	Result               string     `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddSliceGroupResponse) Reset()         { *m = AddSliceGroupResponse{} }
func (m *AddSliceGroupResponse) String() string { return proto.CompactTextString(m) }
func (*AddSliceGroupResponse) ProtoMessage()    {}
func (*AddSliceGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{6}
}

func (m *AddSliceGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSliceGroupResponse.Unmarshal(m, b)
}
func (m *AddSliceGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSliceGroupResponse.Marshal(b, m, deterministic)
}
func (m *AddSliceGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSliceGroupResponse.Merge(m, src)
}
func (m *AddSliceGroupResponse) XXX_Size() int {
	return xxx_messageInfo_AddSliceGroupResponse.Size(m)
}
func (m *AddSliceGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSliceGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSliceGroupResponse proto.InternalMessageInfo

func (m *AddSliceGroupResponse) GetType() ResultType {
	if m != nil {
		return m.Type
	}
	return ResultType_FAIL
}

func (m *AddSliceGroupResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type AddSliceResponse struct {
	Type                 ResultType `protobuf:"varint,1,opt,name=type,proto3,enum=onossliceservice.ResultType" json:"type,omitempty"`
	Result               string     `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddSliceResponse) Reset()         { *m = AddSliceResponse{} }
func (m *AddSliceResponse) String() string { return proto.CompactTextString(m) }
func (*AddSliceResponse) ProtoMessage()    {}
func (*AddSliceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{7}
}

func (m *AddSliceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSliceResponse.Unmarshal(m, b)
}
func (m *AddSliceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSliceResponse.Marshal(b, m, deterministic)
}
func (m *AddSliceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSliceResponse.Merge(m, src)
}
func (m *AddSliceResponse) XXX_Size() int {
	return xxx_messageInfo_AddSliceResponse.Size(m)
}
func (m *AddSliceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSliceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSliceResponse proto.InternalMessageInfo

func (m *AddSliceResponse) GetType() ResultType {
	if m != nil {
		return m.Type
	}
	return ResultType_FAIL
}

func (m *AddSliceResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type PortStatus struct {
	Identifier           string       `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Status               DeviceStatus `protobuf:"varint,2,opt,name=status,proto3,enum=onossliceservice.DeviceStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PortStatus) Reset()         { *m = PortStatus{} }
func (m *PortStatus) String() string { return proto.CompactTextString(m) }
func (*PortStatus) ProtoMessage()    {}
func (*PortStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{8}
}

func (m *PortStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortStatus.Unmarshal(m, b)
}
func (m *PortStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortStatus.Marshal(b, m, deterministic)
}
func (m *PortStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortStatus.Merge(m, src)
}
func (m *PortStatus) XXX_Size() int {
	return xxx_messageInfo_PortStatus.Size(m)
}
func (m *PortStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PortStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PortStatus proto.InternalMessageInfo

func (m *PortStatus) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *PortStatus) GetStatus() DeviceStatus {
	if m != nil {
		return m.Status
	}
	return DeviceStatus_UP
}

type DeviceStatusResponse struct {
	Identifier           string        `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Type                 DeviceType    `protobuf:"varint,2,opt,name=type,proto3,enum=onossliceservice.DeviceType" json:"type,omitempty"`
	Status               DeviceStatus  `protobuf:"varint,3,opt,name=status,proto3,enum=onossliceservice.DeviceStatus" json:"status,omitempty"`
	PortStatus           []*PortStatus `protobuf:"bytes,4,rep,name=portStatus,proto3" json:"portStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeviceStatusResponse) Reset()         { *m = DeviceStatusResponse{} }
func (m *DeviceStatusResponse) String() string { return proto.CompactTextString(m) }
func (*DeviceStatusResponse) ProtoMessage()    {}
func (*DeviceStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{9}
}

func (m *DeviceStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceStatusResponse.Unmarshal(m, b)
}
func (m *DeviceStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceStatusResponse.Marshal(b, m, deterministic)
}
func (m *DeviceStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceStatusResponse.Merge(m, src)
}
func (m *DeviceStatusResponse) XXX_Size() int {
	return xxx_messageInfo_DeviceStatusResponse.Size(m)
}
func (m *DeviceStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceStatusResponse proto.InternalMessageInfo

func (m *DeviceStatusResponse) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *DeviceStatusResponse) GetType() DeviceType {
	if m != nil {
		return m.Type
	}
	return DeviceType_WB_OLT_1G
}

func (m *DeviceStatusResponse) GetStatus() DeviceStatus {
	if m != nil {
		return m.Status
	}
	return DeviceStatus_UP
}

func (m *DeviceStatusResponse) GetPortStatus() []*PortStatus {
	if m != nil {
		return m.PortStatus
	}
	return nil
}

type GetETCDResponse struct {
	Type                 ResultType `protobuf:"varint,1,opt,name=type,proto3,enum=onossliceservice.ResultType" json:"type,omitempty"`
	Results              string     `protobuf:"bytes,2,opt,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetETCDResponse) Reset()         { *m = GetETCDResponse{} }
func (m *GetETCDResponse) String() string { return proto.CompactTextString(m) }
func (*GetETCDResponse) ProtoMessage()    {}
func (*GetETCDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_020609b4ea7088de, []int{10}
}

func (m *GetETCDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetETCDResponse.Unmarshal(m, b)
}
func (m *GetETCDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetETCDResponse.Marshal(b, m, deterministic)
}
func (m *GetETCDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetETCDResponse.Merge(m, src)
}
func (m *GetETCDResponse) XXX_Size() int {
	return xxx_messageInfo_GetETCDResponse.Size(m)
}
func (m *GetETCDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetETCDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetETCDResponse proto.InternalMessageInfo

func (m *GetETCDResponse) GetType() ResultType {
	if m != nil {
		return m.Type
	}
	return ResultType_FAIL
}

func (m *GetETCDResponse) GetResults() string {
	if m != nil {
		return m.Results
	}
	return ""
}

func init() {
	proto.RegisterEnum("onossliceservice.ResultType", ResultType_name, ResultType_value)
	proto.RegisterEnum("onossliceservice.DbaType", DbaType_name, DbaType_value)
	proto.RegisterEnum("onossliceservice.DeviceStatus", DeviceStatus_name, DeviceStatus_value)
	proto.RegisterEnum("onossliceservice.DeviceType", DeviceType_name, DeviceType_value)
	proto.RegisterType((*UniTags)(nil), "onossliceservice.UniTags")
	proto.RegisterType((*BandwidthInfos)(nil), "onossliceservice.BandwidthInfos")
	proto.RegisterType((*AddSliceGroupRequest)(nil), "onossliceservice.AddSliceGroupRequest")
	proto.RegisterType((*AddSliceRequest)(nil), "onossliceservice.AddSliceRequest")
	proto.RegisterType((*DeviceStatusRequest)(nil), "onossliceservice.DeviceStatusRequest")
	proto.RegisterType((*GetETCDRequest)(nil), "onossliceservice.GetETCDRequest")
	proto.RegisterType((*AddSliceGroupResponse)(nil), "onossliceservice.AddSliceGroupResponse")
	proto.RegisterType((*AddSliceResponse)(nil), "onossliceservice.AddSliceResponse")
	proto.RegisterType((*PortStatus)(nil), "onossliceservice.PortStatus")
	proto.RegisterType((*DeviceStatusResponse)(nil), "onossliceservice.DeviceStatusResponse")
	proto.RegisterType((*GetETCDResponse)(nil), "onossliceservice.GetETCDResponse")
}

func init() { proto.RegisterFile("voltha_protos/slice_service.proto", fileDescriptor_020609b4ea7088de) }

var fileDescriptor_020609b4ea7088de = []byte{
	// 823 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x8e, 0xda, 0x46,
	0x14, 0xc6, 0x86, 0x62, 0x38, 0x04, 0x70, 0x27, 0x49, 0xe5, 0x6c, 0xdb, 0x94, 0x75, 0xd5, 0x04,
	0x21, 0x2d, 0x50, 0xa2, 0xad, 0xaa, 0xaa, 0x17, 0xe5, 0x67, 0x8b, 0x56, 0x8d, 0x16, 0x64, 0xb3,
	0x8a, 0x5a, 0xb5, 0xb2, 0x06, 0x3c, 0xb0, 0x96, 0x58, 0x8f, 0xeb, 0x19, 0x88, 0xf2, 0x06, 0x7d,
	0x80, 0xde, 0xf7, 0xcd, 0xfa, 0x20, 0xbd, 0xaa, 0x3c, 0x63, 0x83, 0x81, 0x0d, 0xa8, 0x55, 0x2e,
	0xcf, 0xff, 0x77, 0xbe, 0xef, 0x78, 0x0c, 0xe7, 0x6b, 0xba, 0xe4, 0x77, 0xd8, 0x09, 0x42, 0xca,
	0x29, 0x6b, 0xb1, 0xa5, 0x37, 0x23, 0x0e, 0x23, 0xe1, 0xda, 0x9b, 0x91, 0xa6, 0x70, 0x22, 0x9d,
	0xfa, 0x94, 0x89, 0x40, 0xec, 0x37, 0x5d, 0xd0, 0x6e, 0x7d, 0x6f, 0x82, 0x17, 0x0c, 0x9d, 0x41,
	0x31, 0xa0, 0xbe, 0x33, 0x73, 0x38, 0x5e, 0x18, 0x4a, 0x4d, 0xa9, 0x17, 0x2d, 0x2d, 0xa0, 0x7e,
	0x7f, 0x82, 0x17, 0xc8, 0x84, 0xf2, 0xca, 0xf7, 0x9c, 0x80, 0x86, 0xdc, 0xf1, 0xf1, 0x3d, 0x31,
	0x54, 0x11, 0x2f, 0xad, 0x7c, 0x6f, 0x4c, 0x43, 0x7e, 0x83, 0xef, 0x09, 0x7a, 0x06, 0x05, 0x77,
	0x8a, 0x1d, 0xfe, 0x2e, 0x20, 0x46, 0x56, 0x96, 0xbb, 0x53, 0x3c, 0x79, 0x17, 0x10, 0xf3, 0x07,
	0xa8, 0xf4, 0xb0, 0xef, 0xbe, 0xf5, 0x5c, 0x7e, 0x77, 0xed, 0xcf, 0x29, 0x43, 0x15, 0x50, 0xc3,
	0xb9, 0x98, 0x52, 0xb6, 0xd4, 0x70, 0x2e, 0x6c, 0x2c, 0xba, 0x46, 0x36, 0x16, 0x36, 0x13, 0x6d,
	0x22, 0x9b, 0x99, 0x7f, 0x2a, 0xf0, 0xa4, 0xeb, 0xba, 0x76, 0x84, 0x7d, 0x18, 0xd2, 0x55, 0x60,
	0x91, 0xdf, 0x57, 0x84, 0xf1, 0x68, 0xaa, 0xdc, 0xd4, 0x73, 0xe3, 0x76, 0x9a, 0xb0, 0xaf, 0x5d,
	0xf4, 0x29, 0x14, 0x5d, 0xb2, 0x8e, 0x63, 0x12, 0x70, 0x41, 0x3a, 0x64, 0x70, 0xbb, 0x8d, 0x84,
	0x5b, 0x08, 0x92, 0x55, 0x5e, 0x42, 0x95, 0x53, 0x8e, 0x97, 0xce, 0x34, 0x41, 0x6d, 0xe4, 0x44,
	0xef, 0x8a, 0x70, 0x6f, 0x76, 0x31, 0xff, 0x52, 0xa1, 0x9a, 0xc0, 0x4a, 0x10, 0x7d, 0x0e, 0x20,
	0x11, 0x89, 0xd6, 0x92, 0xc8, 0xa2, 0xf0, 0x24, 0x34, 0x6d, 0x00, 0xab, 0x47, 0x00, 0x67, 0x8f,
	0x01, 0xce, 0xed, 0x01, 0xbe, 0x80, 0x1c, 0xc7, 0x0b, 0x66, 0x7c, 0x54, 0x53, 0xea, 0xa5, 0xce,
	0xb3, 0xe6, 0xbe, 0xce, 0xcd, 0x58, 0x64, 0x4b, 0xa4, 0xa1, 0xef, 0x40, 0x9b, 0xbe, 0x15, 0x42,
	0x18, 0x79, 0x51, 0x51, 0x3b, 0xac, 0xd8, 0x15, 0xcc, 0x4a, 0x0a, 0xd0, 0x05, 0x20, 0x1e, 0xe2,
	0xf9, 0xdc, 0x9b, 0x39, 0x33, 0xea, 0x73, 0xec, 0xf9, 0x24, 0x64, 0x86, 0x56, 0xcb, 0xd6, 0xcb,
	0xd6, 0xc7, 0x71, 0xa4, 0xbf, 0x09, 0x98, 0x4f, 0xe1, 0xf1, 0x40, 0xac, 0x60, 0x73, 0xcc, 0x57,
	0x2c, 0x26, 0xc9, 0xd4, 0xa1, 0x32, 0x24, 0xfc, 0x6a, 0xd2, 0x1f, 0x24, 0x1e, 0x0c, 0x4f, 0xf7,
	0x04, 0x66, 0x01, 0xf5, 0x19, 0x41, 0x6d, 0xc8, 0x89, 0x9b, 0x8a, 0x98, 0xac, 0x74, 0x3e, 0x3b,
	0x44, 0x6a, 0x11, 0xb6, 0x5a, 0xf2, 0xe8, 0xd0, 0x2c, 0x91, 0x89, 0x3e, 0x81, 0x7c, 0x28, 0x7c,
	0xb1, 0xea, 0xb1, 0x65, 0xfe, 0x0a, 0xfa, 0x56, 0xac, 0x0f, 0xde, 0xdd, 0x05, 0x88, 0xbe, 0x05,
	0xb9, 0x27, 0x7a, 0x0e, 0xe0, 0xb9, 0xc4, 0xe7, 0xde, 0xdc, 0x23, 0x61, 0x7c, 0x05, 0x29, 0x0f,
	0xfa, 0x06, 0xf2, 0x4c, 0x64, 0x8a, 0x2e, 0x95, 0xce, 0xf3, 0xc3, 0xc9, 0x3b, 0xbc, 0xc5, 0xd9,
	0xe6, 0xdf, 0x0a, 0x3c, 0xd9, 0x25, 0x34, 0x5e, 0xe4, 0xd4, 0xc0, 0x64, 0x51, 0xf5, 0x7d, 0x8b,
	0xca, 0xae, 0xa9, 0x45, 0xb7, 0x10, 0xb3, 0xff, 0x05, 0x22, 0xfa, 0x1e, 0x20, 0xd8, 0x10, 0x61,
	0xe4, 0x6a, 0xd9, 0x7a, 0xe9, 0xa1, 0x79, 0x5b, 0xb2, 0xac, 0x54, 0xbe, 0xf9, 0x1b, 0x54, 0x37,
	0x97, 0xf1, 0xbf, 0x35, 0x32, 0x40, 0x93, 0xaa, 0xb0, 0x58, 0xa4, 0xc4, 0x6c, 0x7c, 0x09, 0xb0,
	0xcd, 0x46, 0x05, 0xc8, 0xfd, 0xd8, 0xbd, 0x7e, 0xad, 0x67, 0x50, 0x09, 0x34, 0xfb, 0xb6, 0xdf,
	0xbf, 0xb2, 0x6d, 0x5d, 0x69, 0xbc, 0x02, 0x6d, 0x20, 0x9f, 0x2e, 0xf4, 0x18, 0xaa, 0x83, 0x5e,
	0xd7, 0x99, 0xfc, 0x3c, 0xbe, 0x72, 0x6c, 0xcb, 0x19, 0xf4, 0xba, 0x7a, 0x66, 0xc7, 0xd9, 0x1f,
	0x09, 0xa7, 0xd2, 0xa8, 0xc1, 0xa3, 0x34, 0x1d, 0x28, 0x0f, 0xea, 0xed, 0x58, 0xcf, 0x44, 0x33,
	0x06, 0xa3, 0x37, 0x37, 0xba, 0xd2, 0xf8, 0x09, 0x60, 0x4b, 0x32, 0x2a, 0x43, 0xf1, 0x4d, 0xcf,
	0x19, 0xbd, 0x9e, 0x38, 0x5f, 0x0f, 0xf5, 0x0c, 0xaa, 0x00, 0x24, 0x66, 0x7b, 0xa8, 0x2b, 0x29,
	0xbb, 0x73, 0x39, 0xd4, 0xd5, 0x94, 0x7d, 0xd9, 0x1e, 0xea, 0xd9, 0xce, 0x3f, 0x2a, 0x3c, 0x12,
	0xa7, 0x6c, 0x4b, 0x12, 0xd0, 0x14, 0xca, 0x3b, 0x1f, 0x10, 0x7a, 0x71, 0x48, 0xd4, 0x43, 0x4f,
	0xe8, 0xd9, 0xcb, 0x93, 0x79, 0x52, 0x07, 0x33, 0x83, 0x6c, 0x28, 0x24, 0x21, 0x74, 0xfe, 0xfe,
	0xb2, 0xa4, 0xb3, 0x79, 0x2c, 0x65, 0xd3, 0xd4, 0x49, 0x88, 0xb3, 0x48, 0x74, 0x07, 0xe8, 0xab,
	0x13, 0x77, 0x16, 0x37, 0x7f, 0x71, 0x2a, 0x4d, 0x0e, 0x68, 0x2b, 0x68, 0x0c, 0x5a, 0x7c, 0x52,
	0xe8, 0x81, 0x87, 0x6e, 0xf7, 0x1d, 0x3a, 0x3b, 0x3f, 0x92, 0x91, 0x40, 0xee, 0x05, 0xf0, 0x05,
	0x0d, 0x17, 0x4d, 0xc2, 0x43, 0x6f, 0x9b, 0xde, 0x4c, 0x17, 0xf5, 0xf4, 0xd1, 0xcd, 0xc8, 0x4e,
	0x0b, 0xf4, 0xcb, 0xb7, 0x0b, 0x8f, 0xdf, 0xad, 0xa6, 0xcd, 0x19, 0xbd, 0x6f, 0xd1, 0x80, 0xf8,
	0x33, 0x1a, 0xba, 0x2d, 0xf9, 0xd3, 0xbe, 0x88, 0x7f, 0xda, 0xeb, 0xcb, 0xd6, 0x82, 0xb6, 0xf6,
	0x01, 0xfc, 0xa1, 0x28, 0xd3, 0xbc, 0xc8, 0x78, 0xf5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0x2d, 0x28, 0x30, 0xe6, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SliceServiceClient is the client API for SliceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SliceServiceClient interface {
	AddSliceGroup(ctx context.Context, in *AddSliceGroupRequest, opts ...grpc.CallOption) (*AddSliceGroupResponse, error)
	AddSlice(ctx context.Context, in *AddSliceRequest, opts ...grpc.CallOption) (*AddSliceResponse, error)
	DeviceReport(ctx context.Context, in *DeviceStatusRequest, opts ...grpc.CallOption) (SliceService_DeviceReportClient, error)
	GetETCD(ctx context.Context, in *GetETCDRequest, opts ...grpc.CallOption) (*GetETCDResponse, error)
}

type sliceServiceClient struct {
	cc *grpc.ClientConn
}

func NewSliceServiceClient(cc *grpc.ClientConn) SliceServiceClient {
	return &sliceServiceClient{cc}
}

func (c *sliceServiceClient) AddSliceGroup(ctx context.Context, in *AddSliceGroupRequest, opts ...grpc.CallOption) (*AddSliceGroupResponse, error) {
	out := new(AddSliceGroupResponse)
	err := c.cc.Invoke(ctx, "/onossliceservice.SliceService/AddSliceGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliceServiceClient) AddSlice(ctx context.Context, in *AddSliceRequest, opts ...grpc.CallOption) (*AddSliceResponse, error) {
	out := new(AddSliceResponse)
	err := c.cc.Invoke(ctx, "/onossliceservice.SliceService/AddSlice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliceServiceClient) DeviceReport(ctx context.Context, in *DeviceStatusRequest, opts ...grpc.CallOption) (SliceService_DeviceReportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SliceService_serviceDesc.Streams[0], "/onossliceservice.SliceService/DeviceReport", opts...)
	if err != nil {
		return nil, err
	}
	x := &sliceServiceDeviceReportClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SliceService_DeviceReportClient interface {
	Recv() (*DeviceStatusResponse, error)
	grpc.ClientStream
}

type sliceServiceDeviceReportClient struct {
	grpc.ClientStream
}

func (x *sliceServiceDeviceReportClient) Recv() (*DeviceStatusResponse, error) {
	m := new(DeviceStatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sliceServiceClient) GetETCD(ctx context.Context, in *GetETCDRequest, opts ...grpc.CallOption) (*GetETCDResponse, error) {
	out := new(GetETCDResponse)
	err := c.cc.Invoke(ctx, "/onossliceservice.SliceService/GetETCD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SliceServiceServer is the server API for SliceService service.
type SliceServiceServer interface {
	AddSliceGroup(context.Context, *AddSliceGroupRequest) (*AddSliceGroupResponse, error)
	AddSlice(context.Context, *AddSliceRequest) (*AddSliceResponse, error)
	DeviceReport(*DeviceStatusRequest, SliceService_DeviceReportServer) error
	GetETCD(context.Context, *GetETCDRequest) (*GetETCDResponse, error)
}

// UnimplementedSliceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSliceServiceServer struct {
}

func (*UnimplementedSliceServiceServer) AddSliceGroup(ctx context.Context, req *AddSliceGroupRequest) (*AddSliceGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSliceGroup not implemented")
}
func (*UnimplementedSliceServiceServer) AddSlice(ctx context.Context, req *AddSliceRequest) (*AddSliceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSlice not implemented")
}
func (*UnimplementedSliceServiceServer) DeviceReport(req *DeviceStatusRequest, srv SliceService_DeviceReportServer) error {
	return status.Errorf(codes.Unimplemented, "method DeviceReport not implemented")
}
func (*UnimplementedSliceServiceServer) GetETCD(ctx context.Context, req *GetETCDRequest) (*GetETCDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetETCD not implemented")
}

func RegisterSliceServiceServer(s *grpc.Server, srv SliceServiceServer) {
	s.RegisterService(&_SliceService_serviceDesc, srv)
}

func _SliceService_AddSliceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSliceGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SliceServiceServer).AddSliceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onossliceservice.SliceService/AddSliceGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SliceServiceServer).AddSliceGroup(ctx, req.(*AddSliceGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SliceService_AddSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SliceServiceServer).AddSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onossliceservice.SliceService/AddSlice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SliceServiceServer).AddSlice(ctx, req.(*AddSliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SliceService_DeviceReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeviceStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SliceServiceServer).DeviceReport(m, &sliceServiceDeviceReportServer{stream})
}

type SliceService_DeviceReportServer interface {
	Send(*DeviceStatusResponse) error
	grpc.ServerStream
}

type sliceServiceDeviceReportServer struct {
	grpc.ServerStream
}

func (x *sliceServiceDeviceReportServer) Send(m *DeviceStatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SliceService_GetETCD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetETCDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SliceServiceServer).GetETCD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onossliceservice.SliceService/GetETCD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SliceServiceServer).GetETCD(ctx, req.(*GetETCDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SliceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onossliceservice.SliceService",
	HandlerType: (*SliceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSliceGroup",
			Handler:    _SliceService_AddSliceGroup_Handler,
		},
		{
			MethodName: "AddSlice",
			Handler:    _SliceService_AddSlice_Handler,
		},
		{
			MethodName: "GetETCD",
			Handler:    _SliceService_GetETCD_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DeviceReport",
			Handler:       _SliceService_DeviceReport_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "voltha_protos/slice_service.proto",
}
