// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voltha_protos/olt_inter_adapter_service.proto

package org.opencord.voltha.olt_inter_adapter_service;

public final class VolthaOltInterAdapterService {
  private VolthaOltInterAdapterService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-voltha_protos/olt_inter_adapter_servic" +
      "e.proto\022\031olt_inter_adapter_service\032\032volt" +
      "ha_protos/common.proto\032\033google/protobuf/" +
      "empty.proto\032!voltha_protos/inter_adapter" +
      ".proto\032\032voltha_protos/health.proto2\224\002\n\026O" +
      "ltInterAdapterService\022;\n\017GetHealthStatus" +
      "\022\022.common.Connection\032\024.health.HealthStat" +
      "us\022F\n\020ProxyOmciRequest\022\032.inter_adapter.O" +
      "mciMessage\032\026.google.protobuf.Empty\022u\n\026Ge" +
      "tTechProfileInstance\0220.inter_adapter.Tec" +
      "hProfileInstanceRequestMessage\032).inter_a" +
      "dapter.TechProfileDownloadMessageB\220\001\n-or" +
      "g.opencord.voltha.olt_inter_adapter_serv" +
      "iceB\034VolthaOltInterAdapterServiceZAgithu" +
      "b.com/opencord/voltha-protos/v5/go/olt_i" +
      "nter_adapter_serviceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.opencord.voltha.Common.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          org.opencord.voltha.inter_adapter.InterAdapter.getDescriptor(),
          org.opencord.voltha.health.Health.getDescriptor(),
        }, assigner);
    org.opencord.voltha.Common.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    org.opencord.voltha.inter_adapter.InterAdapter.getDescriptor();
    org.opencord.voltha.health.Health.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
