// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voltha_protos/adapter_service.proto

package org.opencord.voltha.adapter_service;

public final class VolthaAdapterService {
  private VolthaAdapterService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#voltha_protos/adapter_service.proto\022\017a" +
      "dapter_service\032\033google/protobuf/empty.pr" +
      "oto\032\032voltha_protos/common.proto\032 voltha_" +
      "protos/core_adapter.proto\032\032voltha_protos" +
      "/device.proto\032\036voltha_protos/extensions." +
      "proto\032\032voltha_protos/health.proto\032\032volth" +
      "a_protos/voltha.proto\032\035voltha_protos/omc" +
      "i_test.proto\032\032voltha_protos/events.proto" +
      "\032\037voltha_protos/bossopenolt.proto2\200;\n\016Ad" +
      "apterService\022;\n\017GetHealthStatus\022\022.common" +
      ".Connection\032\024.health.HealthStatus\0225\n\013Ado" +
      "ptDevice\022\016.device.Device\032\026.google.protob" +
      "uf.Empty\0229\n\017ReconcileDevice\022\016.device.Dev" +
      "ice\032\026.google.protobuf.Empty\0226\n\014DeleteDev" +
      "ice\022\016.device.Device\032\026.google.protobuf.Em" +
      "pty\0227\n\rDisableDevice\022\016.device.Device\032\026.g" +
      "oogle.protobuf.Empty\0228\n\016ReEnableDevice\022\016" +
      ".device.Device\032\026.google.protobuf.Empty\0226" +
      "\n\014RebootDevice\022\016.device.Device\032\026.google." +
      "protobuf.Empty\0228\n\016SelfTestDevice\022\016.devic" +
      "e.Device\032\026.google.protobuf.Empty\022B\n\020GetO" +
      "fpDeviceInfo\022\016.device.Device\032\036.core_adap" +
      "ter.SwitchCapability\0229\n\017ChildDeviceLost\022" +
      "\016.device.Device\032\026.google.protobuf.Empty\022" +
      "2\n\nEnablePort\022\014.device.Port\032\026.google.pro" +
      "tobuf.Empty\0223\n\013DisablePort\022\014.device.Port" +
      "\032\026.google.protobuf.Empty\022B\n\017UpdateFlowsB" +
      "ulk\022\027.core_adapter.BulkFlows\032\026.google.pr" +
      "otobuf.Empty\022R\n\030UpdateFlowsIncrementally" +
      "\022\036.core_adapter.IncrementalFlows\032\026.googl" +
      "e.protobuf.Empty\022@\n\rSendPacketOut\022\027.core" +
      "_adapter.PacketOut\032\026.google.protobuf.Emp" +
      "ty\022E\n\016UpdatePmConfig\022\033.core_adapter.PmCo" +
      "nfigsInfo\032\026.google.protobuf.Empty\022S\n\020Dow" +
      "nloadOnuImage\022\".device.DeviceImageDownlo" +
      "adRequest\032\033.device.DeviceImageResponse\022L" +
      "\n\021GetOnuImageStatus\022\032.device.DeviceImage" +
      "Request\032\033.device.DeviceImageResponse\022O\n\024" +
      "AbortOnuImageUpgrade\022\032.device.DeviceImag" +
      "eRequest\032\033.device.DeviceImageResponse\022-\n" +
      "\014GetOnuImages\022\n.common.ID\032\021.device.OnuIm" +
      "ages\022K\n\020ActivateOnuImage\022\032.device.Device" +
      "ImageRequest\032\033.device.DeviceImageRespons" +
      "e\022I\n\016CommitOnuImage\022\032.device.DeviceImage" +
      "Request\032\033.device.DeviceImageResponse\022O\n\r" +
      "DownloadImage\022\".core_adapter.ImageDownlo" +
      "adMessage\032\025.device.ImageDownload\"\003\210\002\001\022X\n" +
      "\026GetImageDownloadStatus\022\".core_adapter.I" +
      "mageDownloadMessage\032\025.device.ImageDownlo" +
      "ad\"\003\210\002\001\022U\n\023CancelImageDownload\022\".core_ad" +
      "apter.ImageDownloadMessage\032\025.device.Imag" +
      "eDownload\"\003\210\002\001\022U\n\023ActivateImageUpdate\022\"." +
      "core_adapter.ImageDownloadMessage\032\025.devi" +
      "ce.ImageDownload\"\003\210\002\001\022S\n\021RevertImageUpda" +
      "te\022\".core_adapter.ImageDownloadMessage\032\025" +
      ".device.ImageDownload\"\003\210\002\001\022;\n\rStartOmciT" +
      "est\022\026.core_adapter.OMCITest\032\022.omci.TestR" +
      "esponse\022J\n\rSimulateAlarm\022\".core_adapter." +
      "SimulateAlarmMessage\032\025.common.OperationR" +
      "esp\022;\n\rSuppressEvent\022\022.event.EventFilter" +
      "\032\026.google.protobuf.Empty\022=\n\017UnSuppressEv" +
      "ent\022\022.event.EventFilter\032\026.google.protobu" +
      "f.Empty\022H\n\013GetExtValue\022 .core_adapter.Ge" +
      "tExtValueMessage\032\027.extension.ReturnValue" +
      "s\022G\n\013SetExtValue\022 .core_adapter.SetExtVa" +
      "lueMessage\032\026.google.protobuf.Empty\022U\n\016Ge" +
      "tSingleValue\022 .extension.SingleGetValueR" +
      "equest\032!.extension.SingleGetValueRespons" +
      "e\022U\n\016SetSingleValue\022 .extension.SingleSe" +
      "tValueRequest\032!.extension.SingleSetValue" +
      "Response\022H\n\rgetCustomVlan\022\031.bossopenolt." +
      "boss_request\032\034.bossopenolt.GetVlanRespon" +
      "se\022H\n\rGetOltConnect\022\031.bossopenolt.boss_r" +
      "equest\032\034.bossopenolt.OltConnResponse\022J\n\020" +
      "GetOltDeviceInfo\022\031.bossopenolt.boss_requ" +
      "est\032\033.bossopenolt.OltDevResponse\022A\n\013SetP" +
      "mdTxDis\022\031.bossopenolt.boss_request\032\027.bos" +
      "sopenolt.ExecResult\022G\n\013GetPmdTxdis\022\031.bos" +
      "sopenolt.boss_request\032\035.bossopenolt.PmdT" +
      "xdisResponse\022O\n\022GetDevicePmdStatus\022\031.bos" +
      "sopenolt.boss_request\032\036.bossopenolt.PmdS" +
      "tatusResponse\022C\n\rSetDevicePort\022\031.bossope" +
      "nolt.boss_request\032\027.bossopenolt.ExecResu" +
      "lt\022H\n\rGetDevicePort\022\031.bossopenolt.boss_r" +
      "equest\032\034.bossopenolt.GetPortResponse\022?\n\t" +
      "PortReset\022\031.bossopenolt.boss_request\032\027.b" +
      "ossopenolt.ExecResult\022@\n\nSetMtuSize\022\031.bo" +
      "ssopenolt.boss_request\032\027.bossopenolt.Exe" +
      "cResult\022E\n\nGetMtuSize\022\031.bossopenolt.boss" +
      "_request\032\034.bossopenolt.MtuSizeResponse\022=" +
      "\n\007SetVlan\022\031.bossopenolt.boss_request\032\027.b" +
      "ossopenolt.ExecResult\022@\n\nSetLutMode\022\031.bo" +
      "ssopenolt.boss_request\032\027.bossopenolt.Exe" +
      "cResult\022B\n\nGetLutMode\022\031.bossopenolt.boss" +
      "_request\032\031.bossopenolt.ModeResponse\022B\n\014S" +
      "etAgingMode\022\031.bossopenolt.boss_request\032\027" +
      ".bossopenolt.ExecResult\022D\n\014GetAgingMode\022" +
      "\031.bossopenolt.boss_request\032\031.bossopenolt" +
      ".ModeResponse\022B\n\014SetAgingTime\022\031.bossopen" +
      "olt.boss_request\032\027.bossopenolt.ExecResul" +
      "t\022I\n\014GetAgingTime\022\031.bossopenolt.boss_req" +
      "uest\032\036.bossopenolt.AgingTimeResponse\022N\n\020" +
      "GetDeviceMacInfo\022\031.bossopenolt.boss_requ" +
      "est\032\037.bossopenolt.DevMacInfoResponse\022J\n\013" +
      "SetSdnTable\022\031.bossopenolt.boss_request\032 " +
      ".bossopenolt.SdnTableKeyResponse\022G\n\013GetS" +
      "dnTable\022\031.bossopenolt.boss_request\032\035.bos" +
      "sopenolt.SdnTableResponse\022?\n\tSetLength\022\031" +
      ".bossopenolt.boss_request\032\027.bossopenolt." +
      "ExecResult\022C\n\tGetLength\022\031.bossopenolt.bo" +
      "ss_request\032\033.bossopenolt.LengthResponse\022" +
      "B\n\014SetQuietZone\022\031.bossopenolt.boss_reque" +
      "st\032\027.bossopenolt.ExecResult\022I\n\014GetQuietZ" +
      "one\022\031.bossopenolt.boss_request\032\036.bossope" +
      "nolt.QuietZoneResponse\022@\n\nSetFecMode\022\031.b" +
      "ossopenolt.boss_request\032\027.bossopenolt.Ex" +
      "ecResult\022B\n\nGetFecMode\022\031.bossopenolt.bos" +
      "s_request\032\031.bossopenolt.ModeResponse\022@\n\006" +
      "AddOnu\022\031.bossopenolt.boss_request\032\033.boss" +
      "openolt.AddOnuResponse\022B\n\014DeleteOnu25G\022\031" +
      ".bossopenolt.boss_request\032\027.bossopenolt." +
      "ExecResult\022?\n\tAddOnuSla\022\031.bossopenolt.bo" +
      "ss_request\032\027.bossopenolt.ExecResult\022A\n\013C" +
      "learOnuSla\022\031.bossopenolt.boss_request\032\027." +
      "bossopenolt.ExecResult\022J\n\013GetSlaTable\022\031." +
      "bossopenolt.boss_request\032 .bossopenolt.R" +
      "epeatedSlaResponse\022C\n\rSetOnuAllocid\022\031.bo" +
      "ssopenolt.boss_request\032\027.bossopenolt.Exe" +
      "cResult\022C\n\rDelOnuAllocid\022\031.bossopenolt.b" +
      "oss_request\032\027.bossopenolt.ExecResult\022@\n\n" +
      "SetOnuVssn\022\031.bossopenolt.boss_request\032\027." +
      "bossopenolt.ExecResult\022E\n\nGetOnuVssn\022\031.b" +
      "ossopenolt.boss_request\032\034.bossopenolt.On" +
      "uVssnResponse\022I\n\016GetOnuDistance\022\031.bossop" +
      "enolt.boss_request\032\034.bossopenolt.OnuDist" +
      "Response\022G\n\021SetBurstDelimiter\022\031.bossopen" +
      "olt.boss_request\032\027.bossopenolt.ExecResul" +
      "t\022Q\n\021GetBurstDelimiter\022\031.bossopenolt.bos" +
      "s_request\032!.bossopenolt.BurstDelimitResp" +
      "onse\022F\n\020SetBurstPreamble\022\031.bossopenolt.b" +
      "oss_request\032\027.bossopenolt.ExecResult\022Q\n\020" +
      "GetBurstPreamble\022\031.bossopenolt.boss_requ" +
      "est\032\".bossopenolt.BurstPreambleResponse\022" +
      "E\n\017SetBurstVersion\022\031.bossopenolt.boss_re" +
      "quest\032\027.bossopenolt.ExecResult\022O\n\017GetBur" +
      "stVersion\022\031.bossopenolt.boss_request\032!.b" +
      "ossopenolt.BurstVersionResponse\022E\n\017SetBu" +
      "rstProfile\022\031.bossopenolt.boss_request\032\027." +
      "bossopenolt.ExecResult\022O\n\017GetBurstProfil" +
      "e\022\031.bossopenolt.boss_request\032!.bossopeno" +
      "lt.BurstProfileResponse\022S\n\021GetRegisterSt" +
      "atus\022\031.bossopenolt.boss_request\032#.bossop" +
      "enolt.RegisterStatusResponse\022E\n\nGetOnuIn" +
      "fo\022\031.bossopenolt.boss_request\032\034.bossopen" +
      "olt.OnuInfoResponse\022G\n\rGetOmciStatus\022\031.b" +
      "ossopenolt.boss_request\032\033.bossopenolt.St" +
      "atusResponse\022B\n\014SetDsOmciOnu\022\031.bossopeno" +
      "lt.boss_request\032\027.bossopenolt.ExecResult" +
      "\022C\n\rSetDsOmciData\022\031.bossopenolt.boss_req" +
      "uest\032\027.bossopenolt.ExecResult\022I\n\rGetUsOm" +
      "ciData\022\031.bossopenolt.boss_request\032\035.boss" +
      "openolt.OmciDataResponse\022<\n\006SetTod\022\031.bos" +
      "sopenolt.boss_request\032\027.bossopenolt.Exec" +
      "Result\022=\n\006GetTod\022\031.bossopenolt.boss_requ" +
      "est\032\030.bossopenolt.TodResponse\022A\n\013SetData" +
      "Mode\022\031.bossopenolt.boss_request\032\027.bossop" +
      "enolt.ExecResult\022C\n\013GetDataMode\022\031.bossop" +
      "enolt.boss_request\032\031.bossopenolt.ModeRes" +
      "ponse\022C\n\rSetFecDecMode\022\031.bossopenolt.bos" +
      "s_request\032\027.bossopenolt.ExecResult\022E\n\rGe" +
      "tFecDecMode\022\031.bossopenolt.boss_request\032\031" +
      ".bossopenolt.ModeResponse\022B\n\014SetDelimite" +
      "r\022\031.bossopenolt.boss_request\032\027.bossopeno" +
      "lt.ExecResult\022F\n\014GetDelimiter\022\031.bossopen" +
      "olt.boss_request\032\033.bossopenolt.FecDecRes" +
      "ponse\022D\n\016SetErrorPermit\022\031.bossopenolt.bo" +
      "ss_request\032\027.bossopenolt.ExecResult\022M\n\016G" +
      "etErrorPermit\022\031.bossopenolt.boss_request" +
      "\032 .bossopenolt.ErrorPermitResponse\022B\n\014Se" +
      "tPmControl\022\031.bossopenolt.boss_request\032\027." +
      "bossopenolt.ExecResult\022I\n\014GetPmControl\022\031" +
      ".bossopenolt.boss_request\032\036.bossopenolt." +
      "PmControlResponse\022E\n\nGetPmTable\022\031.bossop" +
      "enolt.boss_request\032\034.bossopenolt.PmTable" +
      "Response\022=\n\007SetSAOn\022\031.bossopenolt.boss_r" +
      "equest\032\027.bossopenolt.ExecResult\022>\n\010SetSA" +
      "Off\022\031.bossopenolt.boss_request\032\027.bossope" +
      "nolt.ExecResult\022?\n\025Create_device_handler" +
      "\022\016.device.Device\032\026.google.protobuf.Empty" +
      "\022@\n\nSetSliceBw\022\031.bossopenolt.boss_reques" +
      "t\032\027.bossopenolt.ExecResult\022H\n\nGetSliceBw" +
      "\022\031.bossopenolt.boss_request\032\037.bossopenol" +
      "t.GetSliceBwResponse\022A\n\010SetSlaV2\022\031.bosso" +
      "penolt.boss_request\032\032.bossopenolt.SlaV2R" +
      "esponse\022A\n\010GetSlaV2\022\031.bossopenolt.boss_r" +
      "equest\032\032.bossopenolt.SlaV2Response\022H\n\014Se" +
      "ndOmciData\022\031.bossopenolt.boss_request\032\035." +
      "bossopenolt.BossOmciResponseBt\n#org.open" +
      "cord.voltha.adapter_serviceB\024VolthaAdapt" +
      "erServiceZ7github.com/opencord/voltha-pr" +
      "otos/v5/go/adapter_serviceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          org.opencord.voltha.Common.getDescriptor(),
          org.opencord.voltha.core_adapter.CoreAdapter.getDescriptor(),
          org.opencord.voltha.device.VolthaDevice.getDescriptor(),
          org.opencord.voltha.extension.Extensions.getDescriptor(),
          org.opencord.voltha.health.Health.getDescriptor(),
          org.opencord.voltha.VolthaProtos.getDescriptor(),
          org.opencord.voltha.omci.OmciTest.getDescriptor(),
          org.opencord.voltha.events.Events.getDescriptor(),
          org.opencord.voltha.bossopenolt.VolthaBossOpenOLT.getDescriptor(),
        }, assigner);
    com.google.protobuf.EmptyProto.getDescriptor();
    org.opencord.voltha.Common.getDescriptor();
    org.opencord.voltha.core_adapter.CoreAdapter.getDescriptor();
    org.opencord.voltha.device.VolthaDevice.getDescriptor();
    org.opencord.voltha.extension.Extensions.getDescriptor();
    org.opencord.voltha.health.Health.getDescriptor();
    org.opencord.voltha.VolthaProtos.getDescriptor();
    org.opencord.voltha.omci.OmciTest.getDescriptor();
    org.opencord.voltha.events.Events.getDescriptor();
    org.opencord.voltha.bossopenolt.VolthaBossOpenOLT.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
