// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voltha_protos/core.proto

package org.opencord.voltha.core;

public final class Core {
  private Core() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceTransientStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:core.DeviceTransientState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.core.DeviceTransientState.Types transient_state = 1;</code>
     */
    int getTransientStateValue();
    /**
     * <code>.core.DeviceTransientState.Types transient_state = 1;</code>
     */
    org.opencord.voltha.core.Core.DeviceTransientState.Types getTransientState();
  }
  /**
   * Protobuf type {@code core.DeviceTransientState}
   */
  public  static final class DeviceTransientState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:core.DeviceTransientState)
      DeviceTransientStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceTransientState.newBuilder() to construct.
    private DeviceTransientState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceTransientState() {
      transientState_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceTransientState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              transientState_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opencord.voltha.core.Core.internal_static_core_DeviceTransientState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opencord.voltha.core.Core.internal_static_core_DeviceTransientState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opencord.voltha.core.Core.DeviceTransientState.class, org.opencord.voltha.core.Core.DeviceTransientState.Builder.class);
    }

    /**
     * <pre>
     * Transient State for devices
     * </pre>
     *
     * Protobuf enum {@code core.DeviceTransientState.Types}
     */
    public enum Types
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * The transient state of the device is not set
       * </pre>
       *
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <pre>
       * The state of the device in core is any state, i.e DELETING, DELETED, DELETE_FAILED, NONE.
       * This state is only used for transitions.
       * </pre>
       *
       * <code>ANY = 1;</code>
       */
      ANY(1),
      /**
       * <pre>
       * The device is in FORCE_DELETING state
       * </pre>
       *
       * <code>FORCE_DELETING = 2;</code>
       */
      FORCE_DELETING(2),
      /**
       * <pre>
       * The device is getting deleted from adapter state
       * </pre>
       *
       * <code>DELETING_FROM_ADAPTER = 3;</code>
       */
      DELETING_FROM_ADAPTER(3),
      /**
       * <pre>
       * The device is deleted from adapter and is getting deleted in core.
       * </pre>
       *
       * <code>DELETING_POST_ADAPTER_RESPONSE = 4;</code>
       */
      DELETING_POST_ADAPTER_RESPONSE(4),
      /**
       * <pre>
       * State to represent that the device deletion is failed
       * </pre>
       *
       * <code>DELETE_FAILED = 5;</code>
       */
      DELETE_FAILED(5),
      /**
       * <pre>
       * State to represent that reconcile is in progress
       * </pre>
       *
       * <code>RECONCILE_IN_PROGRESS = 6;</code>
       */
      RECONCILE_IN_PROGRESS(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * The transient state of the device is not set
       * </pre>
       *
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <pre>
       * The state of the device in core is any state, i.e DELETING, DELETED, DELETE_FAILED, NONE.
       * This state is only used for transitions.
       * </pre>
       *
       * <code>ANY = 1;</code>
       */
      public static final int ANY_VALUE = 1;
      /**
       * <pre>
       * The device is in FORCE_DELETING state
       * </pre>
       *
       * <code>FORCE_DELETING = 2;</code>
       */
      public static final int FORCE_DELETING_VALUE = 2;
      /**
       * <pre>
       * The device is getting deleted from adapter state
       * </pre>
       *
       * <code>DELETING_FROM_ADAPTER = 3;</code>
       */
      public static final int DELETING_FROM_ADAPTER_VALUE = 3;
      /**
       * <pre>
       * The device is deleted from adapter and is getting deleted in core.
       * </pre>
       *
       * <code>DELETING_POST_ADAPTER_RESPONSE = 4;</code>
       */
      public static final int DELETING_POST_ADAPTER_RESPONSE_VALUE = 4;
      /**
       * <pre>
       * State to represent that the device deletion is failed
       * </pre>
       *
       * <code>DELETE_FAILED = 5;</code>
       */
      public static final int DELETE_FAILED_VALUE = 5;
      /**
       * <pre>
       * State to represent that reconcile is in progress
       * </pre>
       *
       * <code>RECONCILE_IN_PROGRESS = 6;</code>
       */
      public static final int RECONCILE_IN_PROGRESS_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Types valueOf(int value) {
        return forNumber(value);
      }

      public static Types forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return ANY;
          case 2: return FORCE_DELETING;
          case 3: return DELETING_FROM_ADAPTER;
          case 4: return DELETING_POST_ADAPTER_RESPONSE;
          case 5: return DELETE_FAILED;
          case 6: return RECONCILE_IN_PROGRESS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Types>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Types> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Types>() {
              public Types findValueByNumber(int number) {
                return Types.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.opencord.voltha.core.Core.DeviceTransientState.getDescriptor().getEnumTypes().get(0);
      }

      private static final Types[] VALUES = values();

      public static Types valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Types(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:core.DeviceTransientState.Types)
    }

    public static final int TRANSIENT_STATE_FIELD_NUMBER = 1;
    private int transientState_;
    /**
     * <code>.core.DeviceTransientState.Types transient_state = 1;</code>
     */
    public int getTransientStateValue() {
      return transientState_;
    }
    /**
     * <code>.core.DeviceTransientState.Types transient_state = 1;</code>
     */
    public org.opencord.voltha.core.Core.DeviceTransientState.Types getTransientState() {
      @SuppressWarnings("deprecation")
      org.opencord.voltha.core.Core.DeviceTransientState.Types result = org.opencord.voltha.core.Core.DeviceTransientState.Types.valueOf(transientState_);
      return result == null ? org.opencord.voltha.core.Core.DeviceTransientState.Types.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (transientState_ != org.opencord.voltha.core.Core.DeviceTransientState.Types.NONE.getNumber()) {
        output.writeEnum(1, transientState_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (transientState_ != org.opencord.voltha.core.Core.DeviceTransientState.Types.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, transientState_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.opencord.voltha.core.Core.DeviceTransientState)) {
        return super.equals(obj);
      }
      org.opencord.voltha.core.Core.DeviceTransientState other = (org.opencord.voltha.core.Core.DeviceTransientState) obj;

      if (transientState_ != other.transientState_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRANSIENT_STATE_FIELD_NUMBER;
      hash = (53 * hash) + transientState_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.opencord.voltha.core.Core.DeviceTransientState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencord.voltha.core.Core.DeviceTransientState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencord.voltha.core.Core.DeviceTransientState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencord.voltha.core.Core.DeviceTransientState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencord.voltha.core.Core.DeviceTransientState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencord.voltha.core.Core.DeviceTransientState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencord.voltha.core.Core.DeviceTransientState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opencord.voltha.core.Core.DeviceTransientState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opencord.voltha.core.Core.DeviceTransientState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.opencord.voltha.core.Core.DeviceTransientState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opencord.voltha.core.Core.DeviceTransientState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opencord.voltha.core.Core.DeviceTransientState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.opencord.voltha.core.Core.DeviceTransientState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code core.DeviceTransientState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:core.DeviceTransientState)
        org.opencord.voltha.core.Core.DeviceTransientStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opencord.voltha.core.Core.internal_static_core_DeviceTransientState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opencord.voltha.core.Core.internal_static_core_DeviceTransientState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opencord.voltha.core.Core.DeviceTransientState.class, org.opencord.voltha.core.Core.DeviceTransientState.Builder.class);
      }

      // Construct using org.opencord.voltha.core.Core.DeviceTransientState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        transientState_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opencord.voltha.core.Core.internal_static_core_DeviceTransientState_descriptor;
      }

      @java.lang.Override
      public org.opencord.voltha.core.Core.DeviceTransientState getDefaultInstanceForType() {
        return org.opencord.voltha.core.Core.DeviceTransientState.getDefaultInstance();
      }

      @java.lang.Override
      public org.opencord.voltha.core.Core.DeviceTransientState build() {
        org.opencord.voltha.core.Core.DeviceTransientState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.opencord.voltha.core.Core.DeviceTransientState buildPartial() {
        org.opencord.voltha.core.Core.DeviceTransientState result = new org.opencord.voltha.core.Core.DeviceTransientState(this);
        result.transientState_ = transientState_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opencord.voltha.core.Core.DeviceTransientState) {
          return mergeFrom((org.opencord.voltha.core.Core.DeviceTransientState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opencord.voltha.core.Core.DeviceTransientState other) {
        if (other == org.opencord.voltha.core.Core.DeviceTransientState.getDefaultInstance()) return this;
        if (other.transientState_ != 0) {
          setTransientStateValue(other.getTransientStateValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opencord.voltha.core.Core.DeviceTransientState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opencord.voltha.core.Core.DeviceTransientState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int transientState_ = 0;
      /**
       * <code>.core.DeviceTransientState.Types transient_state = 1;</code>
       */
      public int getTransientStateValue() {
        return transientState_;
      }
      /**
       * <code>.core.DeviceTransientState.Types transient_state = 1;</code>
       */
      public Builder setTransientStateValue(int value) {
        transientState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.core.DeviceTransientState.Types transient_state = 1;</code>
       */
      public org.opencord.voltha.core.Core.DeviceTransientState.Types getTransientState() {
        @SuppressWarnings("deprecation")
        org.opencord.voltha.core.Core.DeviceTransientState.Types result = org.opencord.voltha.core.Core.DeviceTransientState.Types.valueOf(transientState_);
        return result == null ? org.opencord.voltha.core.Core.DeviceTransientState.Types.UNRECOGNIZED : result;
      }
      /**
       * <code>.core.DeviceTransientState.Types transient_state = 1;</code>
       */
      public Builder setTransientState(org.opencord.voltha.core.Core.DeviceTransientState.Types value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        transientState_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.core.DeviceTransientState.Types transient_state = 1;</code>
       */
      public Builder clearTransientState() {
        
        transientState_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:core.DeviceTransientState)
    }

    // @@protoc_insertion_point(class_scope:core.DeviceTransientState)
    private static final org.opencord.voltha.core.Core.DeviceTransientState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.opencord.voltha.core.Core.DeviceTransientState();
    }

    public static org.opencord.voltha.core.Core.DeviceTransientState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceTransientState>
        PARSER = new com.google.protobuf.AbstractParser<DeviceTransientState>() {
      @java.lang.Override
      public DeviceTransientState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceTransientState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceTransientState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceTransientState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.opencord.voltha.core.Core.DeviceTransientState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_DeviceTransientState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_DeviceTransientState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030voltha_protos/core.proto\022\004core\"\357\001\n\024Dev" +
      "iceTransientState\0229\n\017transient_state\030\001 \001" +
      "(\0162 .core.DeviceTransientState.Types\"\233\001\n" +
      "\005Types\022\010\n\004NONE\020\000\022\007\n\003ANY\020\001\022\022\n\016FORCE_DELET" +
      "ING\020\002\022\031\n\025DELETING_FROM_ADAPTER\020\003\022\"\n\036DELE" +
      "TING_POST_ADAPTER_RESPONSE\020\004\022\021\n\rDELETE_F" +
      "AILED\020\005\022\031\n\025RECONCILE_IN_PROGRESS\020\006BH\n\030or" +
      "g.opencord.voltha.coreZ,github.com/openc" +
      "ord/voltha-protos/v5/go/coreb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_core_DeviceTransientState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_DeviceTransientState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_DeviceTransientState_descriptor,
        new java.lang.String[] { "TransientState", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
