// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voltha_protos/core_services.proto

package org.opencord.voltha.core_service;

public final class VolthaCoreService {
  private VolthaCoreService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!voltha_protos/core_services.proto\022\014cor" +
      "e_service\032\033google/protobuf/empty.proto\032 " +
      "voltha_protos/core_adapter.proto\032\032voltha" +
      "_protos/common.proto\032\032voltha_protos/devi" +
      "ce.proto\032\032voltha_protos/health.proto2\371\013\n" +
      "\013CoreService\022;\n\017GetHealthStatus\022\022.common" +
      ".Connection\032\024.health.HealthStatus\022L\n\017Reg" +
      "isterAdapter\022!.core_adapter.AdapterRegis" +
      "tration\032\026.google.protobuf.Empty\0226\n\014Devic" +
      "eUpdate\022\016.device.Device\032\026.google.protobu" +
      "f.Empty\0223\n\013PortCreated\022\014.device.Port\032\026.g" +
      "oogle.protobuf.Empty\022I\n\020PortsStateUpdate" +
      "\022\035.core_adapter.PortStateFilter\032\026.google" +
      ".protobuf.Empty\0224\n\016DeleteAllPorts\022\n.comm" +
      "on.ID\032\026.google.protobuf.Empty\0227\n\rGetDevi" +
      "cePort\022\030.core_adapter.PortFilter\032\014.devic" +
      "e.Port\022,\n\017ListDevicePorts\022\n.common.ID\032\r." +
      "device.Ports\022L\n\021DeviceStateUpdate\022\037.core" +
      "_adapter.DeviceStateFilter\032\026.google.prot" +
      "obuf.Empty\022A\n\024DevicePMConfigUpdate\022\021.dev" +
      "ice.PmConfigs\032\026.google.protobuf.Empty\022D\n" +
      "\023ChildDeviceDetected\022\035.core_adapter.Devi" +
      "ceDiscovery\032\016.device.Device\0226\n\020ChildDevi" +
      "cesLost\022\n.common.ID\032\026.google.protobuf.Em" +
      "pty\022:\n\024ChildDevicesDetected\022\n.common.ID\032" +
      "\026.google.protobuf.Empty\022\'\n\tGetDevice\022\n.c" +
      "ommon.ID\032\016.device.Device\022A\n\016GetChildDevi" +
      "ce\022\037.core_adapter.ChildDeviceFilter\032\016.de" +
      "vice.Device\022.\n\017GetChildDevices\022\n.common." +
      "ID\032\017.device.Devices\022>\n\014SendPacketIn\022\026.co" +
      "re_adapter.PacketIn\032\026.google.protobuf.Em" +
      "pty\022H\n\022DeviceReasonUpdate\022\032.core_adapter" +
      ".DeviceReason\032\026.google.protobuf.Empty\022B\n" +
      "\017PortStateUpdate\022\027.core_adapter.PortStat" +
      "e\032\026.google.protobuf.Empty\022;\n\025ReconcileCh" +
      "ildDevices\022\n.common.ID\032\026.google.protobuf" +
      ".Empty\022M\n\036GetChildDeviceWithProxyAddress" +
      "\022\033.device.Device.ProxyAddress\032\016.device.D" +
      "evice\0223\n\010GetPorts\022\030.core_adapter.PortFil" +
      "ter\032\r.device.Ports\022N\n\023ChildrenStateUpdat" +
      "e\022\037.core_adapter.DeviceStateFilter\032\026.goo" +
      "gle.protobuf.Empty\022D\n\023UpdateImageDownloa" +
      "d\022\025.device.ImageDownload\032\026.google.protob" +
      "uf.EmptyBk\n org.opencord.voltha.core_ser" +
      "viceB\021VolthaCoreServiceZ4github.com/open" +
      "cord/voltha-protos/v5/go/core_serviceb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          org.opencord.voltha.core_adapter.CoreAdapter.getDescriptor(),
          org.opencord.voltha.Common.getDescriptor(),
          org.opencord.voltha.device.VolthaDevice.getDescriptor(),
          org.opencord.voltha.health.Health.getDescriptor(),
        }, assigner);
    com.google.protobuf.EmptyProto.getDescriptor();
    org.opencord.voltha.core_adapter.CoreAdapter.getDescriptor();
    org.opencord.voltha.Common.getDescriptor();
    org.opencord.voltha.device.VolthaDevice.getDescriptor();
    org.opencord.voltha.health.Health.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
